---
title: "Command line"
session: "08"
subtitle: "Adapted from slides by Alison Hill (RStudio)"
author: Zoë Turner
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "assets/css/my-theme.css", "assets/css/my-fonts.css"]
    seal: false 
    lib_dir: libs
    nature:
      highlightStyle: dracula
      highlightLanguage: ["r", "yaml", "markdown"]
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      in_header: assets/header.html  
params:
  site_link: "https://philosopher-analyst.netlify.app/rmd-workshop/"
  cloud_link: "https://rstudio.cloud/"
  github_link: "https://github.com/Lextuga007/rm_01_basics"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
episode_counter <- 0
knitr::opts_chunk$set(
  collapse = TRUE,   
  comment = "#>"
)
```

```{r packages, include=FALSE}
library(countdown)
library(ymlthis)
library(tidyverse)
library(bakeoff)
library(xaringanExtra)

xaringanExtra::use_clipboard()
xaringanExtra::use_share_again() # need to get the slide button on html view
```

class: title-slide, center, middle

<span class="fa-stack fa-4x">
  <i class="fa fa-circle fa-stack-2x" style="color: #ffffffcc;"></i>
  <strong class="fa-stack-1x" style="color:#e7553c;">`r rmarkdown::metadata$session`</strong>
</span> 

# `r rmarkdown::metadata$title`

